image: python:3.6-alpine

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
    - kubernetes
  variables:
    BUILD_REMOTE: "True"
  script:
    - pip install -r requirements.txt
    - python3 deploy.py
  except:
    - master

deploy:
  stage: deploy
  tags:
    - docker
    - kubernetes
  variables:
    BUILD_REMOTE: "True"
    REQUEST_REVIEW: "True"
    REMOTE_BUILD_SECONDS: "5"
  script:
    - pip install -r requirements.txt
    - python3 deploy.py
  only:
    - master
